server:
  host: 127.0.0.1
  port: 8080
  timeout:
    server: 30
    read: 15
    write: 10
    idle: 5
database:
  connectionName: mpesa-daraja-connection
  driver: mysql
  host: service-mysql
  port: 3306
  name: mpesa-daraja
  user: daraja
  password: 38ur900hsuurpwmrt
  maxIdleConnections: 10
  maxOpenConnections: 20
  maxIdleTime: 30
  maxLifeTime: 30
  batchSize: 1000
  migrationsPath: /app/migrations
  generateStructs: true
mpesa:
  baseUrl: https://sandbox.safaricom.co.ke
  consumerKey:
  consumerSecret:
  urls:
    auth: /oauth/v1/generate?grant_type=client_credentials
    express: /mpesa/stkpush/v1/processrequest
    expressQuery: /mpesa/stkpushquery/v1/query
    c2bRegisterUrl: /mpesa/c2b/v1/registerurl
    b2c: /mpesa/b2c/v3/paymentrequest
    transactionStatus: /mpesa/transactionstatus/v1/query
    accountBalance: /mpesa/accountbalance/v1/query
    reversal: /mpesa/reversal/v1/request
    taxRemittance: /mpesa/b2b/v1/remittax
    businessPayBill: /mpesa/b2b/v1/paymentrequest
    businessBuyGoods: /mpesa/b2b/v1/paymentrequest
