server:
  host: 127.0.0.1
  port: 8000
  timeout:
    server: 30
    read: 15
    write: 10
    idle: 5
database:
  connectionName: mpesa-daraja-connection
  driver: mysql
  host: service-mysql
  port: 3306
  name: mpesa-daraja
  user: daraja
  password: 38ur900hsuurpwmrt
  maxIdleConnections: 10
  maxOpenConnections: 20
  maxIdleTime: 30
  maxLifeTime: 30
  migrationsPath: /app/migrations