definitions:
  request.InitiatorRequest:
    properties:
      initiator_credential:
        type: string
      initiator_name:
        type: string
    type: object
  response.ApiResponse:
    properties:
      data: {}
      error_code:
        type: string
      error_message:
        type: string
      response_code:
        type: string
      response_message:
        type: string
      time_stamp:
        type: string
    type: object
info:
  contact: {}
paths:
  /initiators/create:
    post:
      consumes:
      - application/json
      description: Create initiator details to be used to API auth
      parameters:
      - description: initiator
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.InitiatorRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponse'
      summary: Create an Initiator object
      tags:
      - initiator
swagger: "2.0"
